### ISSUE TITLE
classnames not found

### ISSUE THREAD

**Issue by offsky** [Zacqary/rubix#3]
Id like to run this and play with it, but I get this compile error in the browser.

![screen shot 2016-10-03 at 8 34 14 am](https://cloud.githubusercontent.com/assets/1110926/19043273/485d063a-8944-11e6-805a-84af7fa4bc2f.png)

`npm install classnames` fixes the problem. Looks like you just need to add this to package.json

**Comment by kuy** [comment]
@offsky I already sent Pull Request #1 .
If you want to try right now, you can resolve the error by installing `classnames` package like this:

```
$ cd rubix
$ npm install --save classnames
```

**Comment by code-shoily** [comment]
@kuy looks like you beat me to it :)

**Comment by Zacqary** [comment]
Sorry for the late reply! My Github email notifications don't seem to be configured correctly.

Thanks for both catching this, both of you! Forgot to `--save` during development. I'll merge the fix in.
