### ISSUE TITLE
A live demo would have been nice

### ISSUE THREAD

**Issue by louisremi** [Zacqary/rubix#4]
Great work!
I'm pretty sure gh-pages would be a good fit to create a live demo.
Thanks!

**Comment by flybayer** [comment]
[now](https://zeit.co/now) would also be a great option! After deploying it, you could alias it to something like `rubix.now.sh`

**Comment by Zacqary** [comment]
I'll get a live demo up and running this weekend. Thanks for the interest!

**Comment by Zacqary** [comment]
All right, got a demo on Github pages.

@flybayer now seems cool, but I'm not sure if it plays nicely with `create-react-app` projects. I tried a deploy [here](https://rubix-fwrcdpakhl.now.sh/) and got

```
Failed to compile.

Error in ./src/index.js Module build failed: Error: EACCES: permission denied, mkdir '/home/nowuser/src/node_modules/.cache' at Error (native) @ multi main
```

I sent them a message to see what's going on on their end.

**Comment by flybayer** [comment]
@Zacqary, `now` works fine with create-react-app. It could be a specific package issue. However, a workaround would be to build it locally then deploy the build directory with [now-serve](https://github.com/zeit/now-serve) which is for deploying static assets.

**Comment by Zacqary** [comment]
Yep, I was able to do [this deploy](https://ns-qqaitqyoim.now.sh/) with `now-serve` and it worked fine. Unfortunately without the benefits of the `/_src` stuff that `now` can do, though. I'll see if I can figure out what's causing the problem when I deploy from source.
